---

dictionaryDefinitions:
  - name: Spellcheck Overrides
    path: ./cspell_dictionary.txt
    addWords: true

dictionaries:
  - overrides

words:
  - CDPATH
  - cdrom
  - checkwinsize
  - cloudinit
  - Colour
  - Containerfile
  - dmacvicar
  - ensurepip
  - gecos
  - gruntfuggly
  - histappend
  - libatomic
  - nodocs
  - procps
  - qcow
  - setopt
  - shopt
  - terrascan
  - tflint
  - tfsec
  - tfupdate
  - tfvars
  - userns
  - vcpu
  - vhost
  - virtio

ignorePaths:
  - "**/.github/CODEOWNERS"
  - "**/.github/settings.yml"
  - "**/.gitignore"
  - "**/.pre-commit-config.yaml"
  - "**/cspell.config.yml"
